python-path = [
    "./atest/robot/resources",
    "./atest/robot/variables",
    "./atest/robot/lib",
]

[env]
BROWSER_HEADLESS = "false"

[profiles.headless.extend-env]
BROWSER_HEADLESS = "true"

# Slow down browser actions for demonstration purposes.
[profiles.demonstration.extend-env]
BROWSER_SLOWMO = "300ms"

# Profile setting enviroment variables to new webapps. 
[profiles.webapps]
hidden = true
# High precedence for loading this profile at last overriding the legacy-webapps properties.
precedence = 100

[profiles.webapps.extend-env]
FRONTEND_TYPE = "webapps"

# Profile setting enviroment variables to legacy webapps.
[profiles.legacy-webapps]
hidden = true
precedence = 10

[profiles.legacy-webapps.extend-env]
FRONTEND_TYPE = "legacy-webapps"

# Profile for running against webapps dev environment.
[profiles.webapps-dev]
inherits = ["webapps"]

[profiles.webapps-dev.extend-env]
FRONTEND_URL = "http://localhost:5173"

# Profile for running against webapps preview environment.
[profiles.webapps-preview]
inherits = ["webapps"]

[profiles.webapps-preview.extend-env]
FRONTEND_URL = "http://localhost:4173"

# Profile for running against operaton. Uses legacy-webapps per default.
# Additional, activate "webapps" profile to use the new webapps instead of legacy-webapps.
[profiles.operaton]
inherits = ["legacy-webapps"]

[profiles.operaton.extend-variables]
ENGINE_NAME = "Operaton"

[profiles.operaton.extend-env]
ENGINE_URL = "http://localhost:8084"
FRONTEND_URL = "http://localhost:8084"

# Profile for running against camunda. Uses legacy-webapps per default.
# Additional, activate "webapps" profile to use the new webapps instead of legacy-webapps.
[profiles.camunda]
inherits = ["legacy-webapps"]

[profiles.camunda.extend-variables]
ENGINE_NAME = "Camunda"

[profiles.camunda.extend-env]
ENGINE_URL = "http://localhost:8088"
FRONTEND_URL = "http://localhost:8088"

[tool.robocop.lint]
ignore = ["wrong-case-in-keyword-name", "missing-doc-keyword"]
