python-path = ["./atest/robot/resources", "./atest/robot/variables", "./atest/robot/lib"]

[env]
BROWSER_HEADLESS="true"

[profiles.webapps.extend-env]
FRONTEND_TYPE="webapps"

[profiles.legacy-webapps.extend-env]
FRONTEND_TYPE="legacy-webapps"

[profiles.dev.extend-env]
WEBAPPS_URL="http://localhost:5173"

[profiles.preview.extend-env]
WEBAPPS_URL="http://localhost:4173"

[profiles.operaton.extend-env]
LEGACY_FRONTEND_URL="http://localhost:8084"

[profiles.camunda.extend-env]
LEGACY_FRONTEND_URL="http://localhost:8088"